/*This script is for the initial setup of the database for this project. It will also reset an active database, and will delete any data from any tables this project uses. The user that is connecting to the database through KNEX must have the appropriate permissions in the database to prevent errors from the server.*/

DROP TABLE IF EXISTS user_list;
DROP TABLE IF EXISTS knex_test_table;

CREATE TABLE knex_test_table (
    testcolumn TEXT
);

INSERT INTO knex_test_table (testcolumn)
	VALUES ('helloknex');

CREATE TABLE user_list (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_username TEXT UNIQUE NOT NULL,
    user_password TEXT NOT NULL,
    user_salt TEXT NOT NULL,
    user_admin BOOLEAN NOT NULL DEFAULT FALSE
);